extract_data_task:
  description: |
    **INPUTS** 

      User Input: '{user_query}'

      Metadata:
      - Last Announcement Class: '{last_announcement_class}'
      - Last Announcement Summary: '{last_announcement_summary}'
      - Last Announcement Event Date: '{last_announcement_event_date}'

    Your task is to use given user input and given metadata to determine the values for the following important parameters:
    1. announcement_class: The class or grade for which the announcement has to be.
    2. announcement_summary: A brief summary which will be used to generate the title and body for draft of the announcement.
    3. announcement_event_date: The date at which the event will occur for which the announcement is being done.

    You must adhere to the following guidelines while determining the values:
    - Announcement Summary: This has to be detailed enough to make sure a good title and body is generated for draft of the announcement
    - Announcement Event Date: The date has to be in YYYY-MM-DD format like 2025-04-05, 2024-10-31, etc. User may use abbreviations like 6th June, August 15, August 21, 2025, etc. You must call "resolve_date_tool" tool to fetch the date from the user input using payload: 
      {"query": user_query}.
    - Announcement Class: This will determine the audience for which the announcement has to be done. It will have values like 10, 7, etc.

    If any of the important parameters are not available either in user input or metadata, send back a follow up question to the user asking for them.

  expected_output: |
    A JSON object with the following fields:
    {
      "announcement_class": This should have the class for which the announcement is. If not present in user input or metadata then send back empty string.
      "announcement_summary": This should have the brief summary for drafting announcement. If not present in user input or metadata then send back empty string.
      "announcement_event_date": This should have the event date for the announcement. If not returned by resolve_date_tool or not present in user input or metadata then send back empty string.
      "response": This should have the user friendly question asking about the necessary parameter which are not available. If all necessary parameters are present in user input or metadata then send back empty string.
    }
  agent: announcement_creator_data_fetcher

formulate_draft_announcement_task:
  description: |
    **INPUTS** 
    Announcement Class: Take announcement_class from previous task
    Announcement Summary: Take announcement_summary from previous task
    Announcement Event Date: Take announcement_event_date from previous task

    Your task is to formulate a draft of the announcement which the instructor wants to make, using the announcement_class, announcement_summary, and announcement_event_date.
    Do not use any information which is not given to you.
    - First curate an eye catchy title using the announcement summary. This will be the title of the draft.
    - Second add the announcement_class for which the announcement is.
    - Third curate a student friendly body using the announcement summary. This will be the body of the draft.
    - Fourth add the announcement_event_date at the end. This should be at the end showcasing when the event will occur.

  expected_output: |
    A JSON object with the following fields:
    {
      "announcement_class": announcement_class
      "announcement_summary": announcement_summary
      "announcement_event_date": announcement_event_date
      "announcement_title": The title generated by you
      "draft_announcement": The draft announcement created by you
    }
  agent: announcement_creator_draft_fetcher
