classify_subject_task:
  description: |
    Student's query: {user_input}
    Supervisor output: {supervisor_output}
    Last discussed subjects list: {last_subject}
    Available subjects list: {available_subjects}
    
    Your task is to understand, analyze and classify or categorize the student query in a cohesive sense.
    Ensure the classification is done precisely from the available subject list. 
    
    In case, supervisor output suggests that the query is a follow up, you should simply refer to the last discussed subjects list.
  expected_output: |
    A JSON object:
    {
      "subjects": Your subject list
    }
  
  agent: subject_classifier

retrieve_info_task:
  description: |
    Student's query: {user_input}
    Student's grade or class: {grade}
    Classified Subject List: Gather the classified subjects from previous task

    Your task is to call the "retrieve_for_subjective_agent" tool to get context and source. Use the tool using this structured input:
    {
      "query": student's query,
      "subject_names": classified subject list,
      "grade": student's grade
    }

  expected_output: |
    A JSON object:
    {
      "context": The context received in the tool response,
      "source": The source received in the tool response
    }
  
  agent: retriever

summarize_relevant_memory:
  description: |
    Student's query: {user_input}
    Conversation History: {conversation_history}

    Your task is to analyze the conversation history to gather relevant and cohesive information that could be useful to answer student's query.
    Ensure that you stick to the conversation history and do not include any other information.
    If conversation history is not having enough information, then you can pass an empty string.
  expected_output: |
    A JSON object:
    {
      "content_from_history": This should include all relevant and cohesive information collected by you. If nothing is relevant then pass an empty string.
    }

  agent: answer_generator


generate_final_answer_task:
  description: |
    Student's query: {user_input}
    Classified Subject List: Gather this list from previous task
    Content from conversation history: Gather this from previous task
    Context from Retriever: Gather this from previous task
    Source of the Context from Retriever: Gather this from previous task

    Your task is to first analyze the content retrived from conversation history, context from the retriever and its source 
    then generate a complete, cohesive and coherent response for student's query.
  expected_output: |
    A JSON object:
    {
      "context": context from retriever
      "source": source of the context from retriever
      "content_from_history": content from conversation history
      "response": This should have the response generated by you for the student's query
      "last_subject": classified subject list
    }

  agent: answer_generator